### ISSUE TITLE
Suggested alt-text for README?

### ISSUE THREAD

**Issue by spcanelon** [dynastyprocess/graphics#1]
Hi @tanho63! I was very excited to get to share the hex today!
As I was posting on Twitter I realized it would be nice for folks who navigate to the repo to have some suggested alt-text they can use when sharing the image. Would you mind adding a suggestion in the README? Here's what I wrote today just as an example:
> Hex logo for xaringan Club inspired by the xaringan logo and the Fight Club soap logo 

And maybe also include a resource for how to add alt-text to images on Twitter? [How to make images accessible for people](https://help.twitter.com/en/using-twitter/picture-descriptions)

**Comment by tanho63** [comment]
Yay! Yeah, I can add something to the README for it.

**Comment by tanho63** [comment]
@spcanelon Done! 

Have you considered eventually automating a twitter bot that responds to the #xaringan tag + any instance of the word "first"? 😀

**Comment by spcanelon** [comment]
It's perfect, thank you!
And wow that twitter bot idea is gold. I don't have those skills though...do you??? Could this be a reverse nerdsnipe? 😆

**Comment by tanho63** [comment]
Lmao 🖐️ warding it off
